# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# This file should contain a [[items]] section for each application you want themed
# You can also set a shell (outside items) on which to run hooks
# Check flavours repository for more information and examples


# Explanation and default values for keys:

# # Through which shell command hooks will run. The command will be replaced in '{}'
# shell = "sh -c '{}'"
#
# [[items]]
# # File to inject to, supports tilde and env var expansion. required
# file = "~/.config/example"
# # Template to use. required
# template = "example"
#
# # Subtemplate to use
# subtemplate = "default"
# # If not rewriting, on which line (usually a comment) to start replacing
# start = "# Start flavours"
# # If not rewriting, on which line (usually a comment) to stop replacing
# end = "# End flavours"
# # Should we rewrite the entire file, instead of using the above delimiters?
# rewrite = false
# # Command to execute after injecting (goes through shell)
# hook = ""
# # Whether this hook should be executed when flavours is ran with lightweight flag
# light = true

shell = "zsh -c '{}'"
#
[[items]]
file = "~/.dotfiles/waybar/dot-config/waybar/style.css"
template = "waybar"
rewrite = true
subtemplate = "default"

[[items]]
file = "~/.dotfiles/dunst/dot-config/dunst/dunstrc"
template = "dunst"
rewrite = true
hook = "killall dunst"

[[items]]
file = "~/.dotfiles/kitty/dot-config/kitty/current-theme.conf"
template = "kitty"
rewrite = true
subtemplate = "default"

[[items]]
file = "~/.dotfiles/wofi/dot-config/wofi/style.css"
template = "wofi"
rewrite = true
subtemplate = "default"

# [[items]]
# file = "~/.dotfiles/starship/dot-config/starship.toml"
# template = "starship"
# rewrite = true
# subtemplate = "default"

[[items]]
file = "~/.dotfiles/hyprland/dot-config/hypr/hyprland.conf"
template = "hyprland"
rewrite = true
subtemplate = "default"
